### ISSUE TITLE
Plugin Breaks edit post JS in WordPress 4.3

### ISSUE THREAD

**Issue by JayWood** [WebDevStudios/CMB2-Date-Range-Field#4]
Ran into an issue today when updating to WordPress 4.3, this line breaks the entire JS on the edit page: [/wds-cmbw-date-range-field.php::131](https://github.com/WebDevStudios/CMB2-Date-Range-Field/blob/master/wds-cmb2-date-range-field.php#L131)

The fatal error, though it points to jQuery, not any script on the project, which is weird.
![](https://gyazo.com/e7a320cde668fbc9b98cc12c4bddc789.png)

Commenting out that form field fixes the JS issue.

**Comment by sb-lc** [comment]
Uncaught TypeError: Cannot use 'in' operator to search for 'length' in false

i get this with wp 4.3 as well, the date range field type is unusable

**Comment by bradp** [comment]
Fixed in #6
