### ISSUE TITLE
Year is stored as "Y" instead of the actual year

### ISSUE THREAD

**Issue by zedejose** [WebDevStudios/CMB2-Date-Range-Field#7]
Not sure if I'm doing something wrong but when defining the field as:

``` php
$cmb->add_field( array(
'name'       => __( 'Test Date Range', 'cmb2' ),
'desc'       => __( 'field description (optional)', 'cmb2' ),
'id'         => $this->field_prefix . 'date_range',
'type'       => 'date_range',
) );
```

This is what gets saved to the database:

`a:2:{s:5:"start";s:6:"9/28/Y";s:3:"end";s:7:"10/31/Y";}`

i.e. the year is saved as "Y" instead of the actual year

**Comment by misfist** [comment]
I'm seeing the same thing. It's being saved as:

`a:2:{s:5:"start";s:6:"10/1/Y";s:3:"end";s:6:"10/4/Y";}`

This might be related to this bug? https://github.com/WebDevStudios/CMB2/issues/300

In addition, although the value is stored, it doesn't display in the metabox after saving the post.

**Comment by davidlonguk** [comment]
Ditto. Seeing the same.

**Comment by davidlonguk** [comment]
Since this plugin appears to be broken and unsupported I thought I'd share a work around I've used.
Create the field as a CMB2 text field and make sure one of the parameters sets a class name of date_range_picker

```
$cmb_schedule->add_field( array(
            'name'  => __( 'Date Range', 'cmb' ),
            'desc'  => __( 'Choose the date range', 'cmb' ),
            'id'    => $prefix . 'date_range',
            'type'  => 'text',
            'attributes' => array(
            'class' => __( 'date_range_picker', 'cmb' ),
            ),
```

then add this JS to run on your admin pages

```
$(function() {
     // add date picker support to dates  taxonomy 


         $(".date_range_picker").datepicker({
            numberOfMonths: 2,
            dateFormat : 'yy-mm-dd', //format your date here
            onSelect: function( selectedDate ) {
                if(!$(this).data().datepicker.first){
                    $(this).data().datepicker.inline = true
                    $(this).data().datepicker.first = selectedDate;
                }else{
                    if(selectedDate > $(this).data().datepicker.first){
                        $(this).val($(this).data().datepicker.first+"_"+selectedDate);
                    }else{
                        $(this).val(selectedDate+"_"+$(this).data().datepicker.first);
                    }
                    $(this).data().datepicker.inline = false;
                }
            },
            onClose:function(){
                delete $(this).data().datepicker.first;
                $(this).data().datepicker.inline = false;
            }
         })
     });
```

**Comment by davidlonguk** [comment]
@jtsternberg Thanks for submitting a fix for this. I have already implemented another solution but may come back and test it out if I get time. Appreciate you supporting this plugin - sorry if my comments offended.

**Comment by jtsternberg** [comment]
No offense taken. It's been over a year since this was reported, and you provided a workaround, so your comments were both truthful and helpful. That's what open source is about. Unfortunately, sometimes things get abandoned or neglected.
